# =============================================================================
# SVML autodetect — mirrors Library/Vectorization/Cmake/utils.cmake SVML probe.
#
# CMake: if the snippet with _mm256_exp_ps / _mm256_cos_ps / _mm256_tanh_ps fails
# for the active SIMD flags AND vectorization is on, VECTORIZATION_ENABLE_SVML is ON.
# If the compile succeeds (e.g. Intel compiler with native SVML), it is OFF.
#
# This repository rule runs one probe per SIMD tier (Unix host) with the same
# flags as bazel/vectorization.bzl vectorization_simd_copts. Windows assumes
# third-party SVML is needed (typical MSVC/clang-cl).
# =============================================================================

def _is_windows(repository_ctx):
    n = repository_ctx.os.name.lower()
    return n == "windows" or n.startswith("win")

def _cxx(repository_ctx):
    cxx = repository_ctx.os.environ.get("CXX", "") or repository_ctx.os.environ.get("CC", "")
    cxx = cxx.strip().strip("\"'")
    if cxx:
        return cxx
    w = repository_ctx.which("c++")
    if w:
        return w
    w = repository_ctx.which("clang++")
    if w:
        return w
    w = repository_ctx.which("g++")
    if w:
        return w
    return ""

# Same probe source as utils.cmake (CheckCXXSourceCompiles).
_PROBE_SRC = """#if defined(_MSC_VER)
#include <intrin.h>
#else
#include <immintrin.h>
#endif
int main() {
  __m256 a, b;
  a = _mm256_setzero_ps();
  b = _mm256_exp_ps(a);
  b = _mm256_cos_ps(a);
  b = _mm256_tanh_ps(a);
  return 0;
}
"""

# Unix flags — keep in sync with vectorization_simd_copts() unix table.
_TIER_UNIX_FLAGS = {
    "sse": ["-msse4.2", "-msse4.1", "-msse2", "-msse"],
    "avx": ["-mavx", "-mf16c"],
    "avx2": ["-mavx2", "-mf16c", "-mfma"],
    "avx512": [
        "-mavx512f",
        "-mavx512dq",
        "-mavx512vl",
        "-mf16c",
        "-mfma",
    ],
}

def _native_svml_compiles(repository_ctx, cxx, flags):
    cmd = [cxx, "-std=c++20"] + flags + ["-c", "probe.cpp", "-o", "probe_svml.o"]
    r = repository_ctx.execute(cmd, quiet = True)
    return r.return_code == 0

def _write_config(repository_ctx, needed_by_tier):
    lines = [
        "# Generated by //bazel:svml_configure.bzl — do not edit.",
        "# SVML_NEEDED_*: True → link @svml (compiler lacks native SVML intrinsics).",
    ]
    for t in ("sse", "avx", "avx2", "avx512"):
        lines.append("SVML_NEEDED_%s = %s" % (t.upper(), needed_by_tier[t]))
    repository_ctx.file("config.bzl", "\n".join(lines) + "\n")
    repository_ctx.file("BUILD.bazel", 'exports_files(["config.bzl"])\n')

def _svml_configure_impl(repository_ctx):
    needed = {t: True for t in _TIER_UNIX_FLAGS}

    if _is_windows(repository_ctx):
        _write_config(repository_ctx, needed)
        return

    cxx = _cxx(repository_ctx)
    if not cxx:
        _write_config(repository_ctx, needed)
        return

    repository_ctx.file("probe.cpp", _PROBE_SRC)

    for tier, flags in _TIER_UNIX_FLAGS.items():
        if _native_svml_compiles(repository_ctx, cxx, flags):
            needed[tier] = False
        else:
            needed[tier] = True

    _write_config(repository_ctx, needed)

svml_configure = repository_rule(
    implementation = _svml_configure_impl,
    local = True,
    environ = [
        "CXX",
        "CC",
        "PATH",
    ],
)
