#=============================================================================
# Quarisma Configuration
# Summary Module

# This module provides a function to print a comprehensive summary of the Quarisma build
# configuration, including compiler settings, enabled features, and optional dependencies.

# Include guard to prevent multiple inclusions
include_guard(GLOBAL)

# Prints accumulated Quarisma configuration summary
function(print_configuration_summary)
  message("")
  message("******** Summary ********")
  message("General:")
  message("  CMake version         : ${CMAKE_VERSION}")
  message("  CMake command         : ${CMAKE_COMMAND}")
  message("  System                : ${CMAKE_SYSTEM_NAME}")
  message("  C++ compiler          : ${CMAKE_CXX_COMPILER}")
  message("  C++ compiler id       : ${PROJECT_COMPILER_ID}")
  message("  C++ compiler version  : ${CMAKE_CXX_COMPILER_VERSION}")
  message("  C++ standard          : ${PROJECT_CXX_STANDARD}")
  message("  Compiler cache        : ${PROJECT_CACHE_BACKEND}")
  message("  Compiler cache program: ${PROJECT_CACHE_PROGRAM}")
  message("  CXX flags             : ${CMAKE_CXX_FLAGS}")
  message("  Shared LD flags       : ${CMAKE_SHARED_LINKER_FLAGS}")
  message("  Static LD flags       : ${CMAKE_STATIC_LINKER_FLAGS}")
  message("  Module LD flags       : ${CMAKE_MODULE_LINKER_FLAGS}")
  message("  Build type            : ${CMAKE_BUILD_TYPE}")
  get_directory_property(tmp DIRECTORY ${PROJECT_SOURCE_DIR} COMPILE_DEFINITIONS)
  message("  Compile definitions   : ${tmp}")
  message("  CMAKE_PREFIX_PATH     : ${CMAKE_PREFIX_PATH}")
  message("  CMAKE_INSTALL_PREFIX  : ${CMAKE_INSTALL_PREFIX}")
  message("")
  if(PROJECT_ENABLE_IWYU)
    message("  IWYU:")
    message("    IWYU executable     : ${PROJECT_IWYU_EXECUTABLE}")
    message("    IWYU arguments      : ${PROJECT_IWYU_ARGS}")
  endif()
  get_directory_property(tmp DIRECTORY ${PROJECT_SOURCE_DIR} COMPILE_DEFINITIONS)
  message("  CMake generator       : ${CMAKE_GENERATOR}")
  message("  CMake build tool      : ${CMAKE_BUILD_TOOL}")
  message("  CMake install prefix  : ${CMAKE_INSTALL_PREFIX}")
  message("  CMake build type      : ${CMAKE_BUILD_TYPE}")
  message("  CMake build options   : ${CMAKE_BUILD_OPTIONS}")
  message("  CMake build flags     : ${CMAKE_BUILD_FLAGS}")
  message("  CMAKE_PREFIX_PATH     : ${CMAKE_PREFIX_PATH}")
  message("  CMAKE_INSTALL_PREFIX  : ${CMAKE_INSTALL_PREFIX}")
  message("  PROJECT_VERSION        : ${PROJECT_VERSION}")
  message("  BUILD_BINARY          : ${PROJECT_BINARY_DIR}")
  message("  PROJECT_DLL_PATHS      : ${PROJECT_DLL_PATHS}")
  message("  DATA_STORE            : ${PROJECT_DATA_STORE}")
  message("  PROJECT_flags:")
  message("    Vectorization       : ${PROJECT_VECTORIZATION_TYPE}")
  if(PARALLEL_ENABLE_TBB)
    set(_parallel_backend "TBB")
  elseif(PARALLEL_ENABLE_OPENMP)
    set(_parallel_backend "OpenMP")
  else()
    set(_parallel_backend "STDThread")
  endif()
  message("    USE_GOLD_LINKER     : ${PROJECT_ENABLE_GOLD_LINKER}")
  message("    Multithreading      : ${_parallel_backend}")
  message("    Logging backend     : ${LOGGING_BACKEND}")
  message("    Profiling backend   : ${PROFILER_TYPE}")
  message("    Cache backend       : ${PROJECT_CACHE_BACKEND}")
  message("    MKL                 : ${PROJECT_ENABLE_MKL}")
  message("    Memkind             : ${MEMORY_ENABLE_MEMKIND}")
  message("    NUMA                : ${MEMORY_ENABLE_NUMA}")
  message("    Sobol 1111          : ${PROJECT_SOBOL_1111}")
  message("    LU Pivoting         : ${PROJECT_LU_PIVOTING}")
  message("    LTO                 : ${PROJECT_ENABLE_LTO}")
  message("    Magic Enum          : ${PROJECT_ENABLE_MAGICENUM}")
  message("    Mimalloc            : ${MEMORY_ENABLE_MIMALLOC}")
  message("    TBB (memory)        : ${MEMORY_ENABLE_TBB}")
  message("    CUDA                : ${MEMORY_ENABLE_CUDA}")
  message("    HIP                 : ${MEMORY_ENABLE_HIPA}")
  message("    Enzyme              : ${CORE_ENABLE_ENZYME}")
  message("    Documentation       : ${PROJECT_BUILD_DOCUMENTATION}")
  message("    External libraries  : ${QUARISMA_ENABLE_EXTERNAL}")

  message("  Build:")
  message("    Shared libs         : ${PROJECT_BUILD_SHARED_LIBS}")
  if(PROJECT_WRAP_PYTHON OR PROJECT_BUILD_WHEEL)
    message("  Python:")
    message("    Build wheel         : ${PROJECT_BUILD_WHEEL}")
    message("    Python version      : ${PROJECT_PYTHON_VERSION}")
    message("    Python executable   : ${Python3_EXECUTABLE}")
    message("    Python site-packages: ${PROJECT_PYTHON_SITE_PACKAGES_SUFFIX}")
  else()
    message("  PYTHON                : OFF")
  endif()
  if(PROJECT_WRAP_JAVA)
    message("  Java:")
    message("    Java version        : ${Java_VERSION_MAJOR}")
    message("    Java executable     : ${Java_JAR_EXECUTABLE}")
    message("    JNI library         : ${PROJECT_JNI_LIBRARIES}")
    message("    JNI includes        : ${PROJECT_JNI_INCLUDE_DIRS}")
  else()
    message("  JAVA                  : OFF")
  endif()
  if(MEMORY_ENABLE_CUDA)
    message("  CUDA:")
    message("    CUDA include path   : ${CUDA_INCLUDE_DIRS}")
    message("    NVCC executable     : ${CUDA_NVCC_EXECUTABLE}")
    message("    NVCC flags          : ${CMAKE_CUDA_FLAGS}")
    message("    CUDA host compiler  : ${CUDA_HOST_COMPILER}")
    message("    NVCC --device-c     : ${CUDA_SEPARABLE_COMPILATION}")
    message("    CUDA version        : ${CUDA_VERSION}")
    message("    CUDA library        : ${PROJECT_CUDA_LIBRARIES}")
    message("    CUDA compiler       : ${CMAKE_CUDA_COMPILER}")
    message("    CUDA includes       : ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}")
  else()
    message("  CUDA                  : OFF")
  endif()
  if(PROJECT_BUILD_TESTING)
    message("  Testing:")
    message("    Google test         : ${PROJECT_ENABLE_GTEST}")
    message("    Benchmark           : ${PROJECT_ENABLE_BENCHMARK}")
    message("    Valgrind            : ${PROJECT_ENABLE_VALGRIND}")
    message("    Coverage            : ${PROJECT_ENABLE_COVERAGE}")
    message("    IWYU                : ${PROJECT_ENABLE_IWYU}")
    message("    Clang-tidy          : ${PROJECT_ENABLE_CLANGTIDY}")
    message("    Clang-tidy fix      : ${PROJECT_ENABLE_FIX}")
    message("    Cppcheck            : ${PROJECT_ENABLE_CPPCHECK}")
    if(PROJECT_ENABLE_SANITIZER)
      message("    Sanitizer           : ${PROJECT_SANITIZER_TYPE}")
    endif()
  endif()

  message("")
endfunction()
