# ============================================================================= Quarisma
# Configuration Summary Module
#
# print_configuration_summary — workspace-wide toolchain and CMake metadata only.
# Per-library CMake flag summaries live at the end of each Library/*/CMakeLists.txt.
# =============================================================================

include_guard(GLOBAL)

function(print_configuration_summary)
  message("")
  message("******** Global build summary ********")
  message("Toolchain:")
  message("  CMake version            : ${CMAKE_VERSION}")
  message("  CMake command            : ${CMAKE_COMMAND}")
  message("  CMake generator          : ${CMAKE_GENERATOR}")
  message("  CMake build tool         : ${CMAKE_BUILD_TOOL}")
  message("  System                   : ${CMAKE_SYSTEM_NAME}")
  message("  C compiler               : ${CMAKE_C_COMPILER}")
  message("  C compiler id            : ${CMAKE_C_COMPILER_ID}")
  message("  C compiler version       : ${CMAKE_C_COMPILER_VERSION}")
  message("  C++ compiler             : ${CMAKE_CXX_COMPILER}")
  message("  C++ compiler id          : ${CMAKE_CXX_COMPILER_ID}")
  message("  C++ compiler version     : ${CMAKE_CXX_COMPILER_VERSION}")
  message("  Default C++ standard     : ${CMAKE_CXX_STANDARD}")
  message("  C++ standard required    : ${CMAKE_CXX_STANDARD_REQUIRED}")
  message("  C++ extensions           : ${CMAKE_CXX_EXTENSIONS}")
  message("  C flags                  : ${CMAKE_C_FLAGS}")
  message("  CXX flags                : ${CMAKE_CXX_FLAGS}")
  message("  Shared linker flags      : ${CMAKE_SHARED_LINKER_FLAGS}")
  message("  Static linker flags      : ${CMAKE_STATIC_LINKER_FLAGS}")
  message("  Module linker flags      : ${CMAKE_MODULE_LINKER_FLAGS}")
  message("  Build type               : ${CMAKE_BUILD_TYPE}")
  message("  IPO / LTO (CMake)        : ${CMAKE_INTERPROCEDURAL_OPTIMIZATION}")
  get_directory_property(_summary_compile_defs DIRECTORY ${PROJECT_SOURCE_DIR} COMPILE_DEFINITIONS)
  message("  Top-level compile defs   : ${_summary_compile_defs}")
  message("Paths:")
  message("  CMAKE_PREFIX_PATH        : ${CMAKE_PREFIX_PATH}")
  message("  CMAKE_INSTALL_PREFIX     : ${CMAKE_INSTALL_PREFIX}")
  message("  PROJECT_SOURCE_DIR       : ${PROJECT_SOURCE_DIR}")
  message("  PROJECT_BINARY_DIR       : ${PROJECT_BINARY_DIR}")
  message("  PROJECT_VERSION          : ${PROJECT_VERSION}")
  if(DEFINED CMAKE_BUILD_OPTIONS)
    message("  CMAKE_BUILD_OPTIONS      : ${CMAKE_BUILD_OPTIONS}")
  endif()
  if(DEFINED CMAKE_BUILD_FLAGS)
    message("  CMAKE_BUILD_FLAGS        : ${CMAKE_BUILD_FLAGS}")
  endif()
  if(DEFINED PROJECT_DLL_PATHS)
    message("  PROJECT_DLL_PATHS        : ${PROJECT_DLL_PATHS}")
  endif()
  if(DEFINED PROJECT_DATA_STORE)
    message("  PROJECT_DATA_STORE       : ${PROJECT_DATA_STORE}")
  endif()
  message("Options:")
  message("  BUILD_SHARED_LIBS        : ${BUILD_SHARED_LIBS}")
  message("  QUARISMA_ENABLE_EXTERNAL : ${QUARISMA_ENABLE_EXTERNAL}")
  message("")
endfunction()
